

## Tips on Cloud Functions

You are unable to use pydub ( ffmpeg ) at Python3.11 and 3.10.
Use 3.9 otherwise you will face errors.

### rerefence

Cloud function do supports pydub ( ffmpeg ), but Python311 and 310 env are unable to include them as base image itself do not include ffmpeg.
<https://issuetracker.google.com/issues/242685280?pli=1>

### errors

```bash
File "/layers/google.python.runtime/python/lib/python3.10/subprocess.py", line 1847, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
```
